### ISSUE TITLE
How to enable HTTPS on the load balancer?

### ISSUE THREAD

**Issue by zulhfreelancer** [enghwa/RoRChat-cdk#2]
Hi Eng Hwa,

I'm trying to enable HTTPS on the load balancer. I tried your code by uncommented on...

* [Line 58-67](https://github.com/enghwa/RoRChat-cdk/blob/master/lib/ecs-fargate-stack.ts#L58-L67)
* [Line 90-92](https://github.com/enghwa/RoRChat-cdk/blob/master/lib/ecs-fargate-stack.ts#L90-L92)

...but it didn't work. Appreciate if you could provide a working example for that.

**Additional information**:

I'm using Cloudflare as nameserver with SSL setting sets to [Full (strict)](https://support.cloudflare.com/hc/en-us/articles/200170416-End-to-end-HTTPS-with-Cloudflare-Part-3-SSL-options#h_8afd8a8d-382d-4694-a2b2-44cbc9f637ef) and I do not wish to point my domain to Route53. I want to keep using Cloudflare as nameserver for my domain and sub-domains.

I want _http**s**://example-app.my-domain.com_ to point to the Rails app's load balancer and my end users should see that URL in their web browser (not redirect).

Thanks.

**Comment by thecloudranger** [comment]
Hi @zulhfreelancer .

The instructions in the README file have been updated on how to map a custom domain with SSL to an ALB, using the aws cli.

The ECS pattern ApplicationLoadBalancedFargateService used in [ecs-fargate-stack.ts](https://github.com/enghwa/RoRChat-cdk/blob/master/lib/ecs-fargate-stack.ts) currently requires a hosted zone created in Route53.

**Comment by zulhfreelancer** [comment]
Thanks @thecloudranger. Looks like we need to use AWS CLI here. Does it possible to automate this using CDK instead?

One more question regarding this code block:

```
aws acm request-certificate \
  --domain-name www.example.com \
  --subject-alternative-names "example.com" \
  --validation-method DNS
``` 

Let say I want to enable HTTPS on _https://example-app.my-domain.com_ (note that it's a sub-domain), should I run the command above using `example-app.my-domain.com` OR `my-domain.com`?

Do I need to repeat the whole process for every sub-domains that I have?

**Comment by enghwa** [comment]
u can create wildcard certs too in ACM, if u have alot of subdomain

**Comment by zulhfreelancer** [comment]
Noted. Thanks.
